import requests
import json
import logging
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# ✅ Настройки Ollama
OLLAMA_BASE_URL = "http://ollama:11434"
OLLAMA_MODEL = "llama3.2"


class AITestGenerator:
    """
    Генерация юнит-тестов с помощью локальной AI модели (Ollama).

    Поддерживаемые режимы:
    - basic: Простые тесты на основе сигнатур функций
    - advanced: Тесты с моками и граничными случаями (AI)
    - full: Комбинация basic + advanced
    """

    def __init__(self, model: str = None, timeout: int = 120):
        self.model = model or OLLAMA_MODEL
        self.timeout = timeout
        self.base_url = OLLAMA_BASE_URL

    def generate_tests(
            self,
            code: str,
            metrics: Dict = None,
            config: Dict = None
    ) -> str:
        """Генерирует тесты на основе кода и конфигурации."""

        config = config or {}
        detail_level = config.get('detail_level', 'basic')
        use_mocks = config.get('use_mocks', False)
        include_edge_cases = config.get('include_edge_cases', True)
        test_framework = config.get('test_framework', 'pytest')

        logger.info(f"🤖 Generating tests: level={detail_level}, mocks={use_mocks}")

        if detail_level == 'basic':
            return self._generate_basic_tests(code, metrics, test_framework)
        else:
            return self._generate_ai_tests(code, metrics, config, test_framework)

    def _generate_basic_tests(
            self,
            code: str,
            metrics: Dict,
            framework: str
    ) -> str:
        """Генерирует простые тесты на основе сигнатур функций (без AI)"""

        import ast

        tests = []
        tests.append('"""Auto-generated tests (basic mode)"""\n')

        if framework == 'pytest':
            tests.append('import pytest\n')
        else:
            tests.append('import unittest\n')

        tests.append('from your_module import *\n\n')

        try:
            tree = ast.parse(code)

            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
                    args = [arg.arg for arg in node.args.args if arg.arg != 'self']

                    if framework == 'pytest':
                        test = f'''
def test_{node.name}_basic():
    """Basic test for {node.name}"""
    # TODO: Add test arguments based on function signature
    # Args: {', '.join(args)}
    result = {node.name}(...)  # TODO: Fill in arguments
    assert result is not None  # TODO: Add proper assertion
'''
                    else:
                        test = f'''
class Test{node.name.capitalize()}(unittest.TestCase):
    def test_{node.name}_basic(self):
        """Basic test for {node.name}"""
        # TODO: Add test arguments
        result = {node.name}(...)
        self.assertIsNotNone(result)
'''
                    tests.append(test)

            tests.append('\n# Generated by Python Test Analyzer\n')

        except Exception as e:
            logger.error(f"Basic test generation failed: {e}")
            tests.append(f'# Error generating tests: {e}\n')

        return '\n'.join(tests)

    def _generate_ai_tests(
            self,
            code: str,
            metrics: Dict,
            config: Dict,
            framework: str
    ) -> str:
        """Генерирует тесты с помощью Ollama AI"""

        # 📝 Формируем промпт
        prompt = self._build_prompt(code, metrics, config, framework)

        try:
            # 🤖 Запрос к Ollama
            response = requests.post(
                f"{self.base_url}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.3,
                        "num_predict": 2000,
                        "timeout": self.timeout
                    }
                },
                timeout=self.timeout
            )

            if response.status_code == 200:
                result = response.json()
                generated_tests = result.get('response', '')
                logger.info(f"✅ AI generated {len(generated_tests)} characters of tests")
                return generated_tests
            else:
                logger.error(f"❌ Ollama API error: {response.status_code}")
                return f"# AI generation failed: HTTP {response.status_code}\n" + \
                    self._generate_basic_tests(code, metrics, framework)

        except requests.exceptions.ConnectionError:
            logger.error("❌ Cannot connect to Ollama. Is it running?")
            return f"# Ollama not available. Using basic tests.\n" + \
                self._generate_basic_tests(code, metrics, framework)
        except Exception as e:
            logger.error(f"❌ AI generation error: {e}")
            return f"# Error: {e}\n" + self._generate_basic_tests(code, metrics, framework)

    def _build_prompt(
            self,
            code: str,
            metrics: Dict,
            config: Dict,
            framework: str
    ) -> str:
        """Строит промпт для AI модели — НАДЁЖНАЯ ВЕРСИЯ (список + join)"""

        use_mocks = config.get('use_mocks', False)
        include_edge_cases = config.get('include_edge_cases', True)

        # ✅ Часть 1: Статический шаблон
        prompt_parts = []

        prompt_parts.append("You are an expert Python developer specializing in test automation.")
        prompt_parts.append("")
        prompt_parts.append("## Task")
        prompt_parts.append("Generate comprehensive unit tests for the following Python code.")
        prompt_parts.append("")
        prompt_parts.append("## Code to Test")
        prompt_parts.append("```python")

        # ✅ Часть 2: Код (ограничиваем размер)
        prompt_parts.append(code[:8000])

        prompt_parts.append("```")
        prompt_parts.append("")

        # ✅ Часть 3: Метрики
        prompt_parts.append("## Code Metrics")
        prompt_parts.append(f"- Functions: {metrics.get('functions_count', 0)}")
        prompt_parts.append(f"- Classes: {metrics.get('classes_count', 0)}")
        prompt_parts.append(f"- Async functions: {metrics.get('async_functions', 0)}")
        prompt_parts.append(f"- Total lines: {metrics.get('total_lines', 0)}")
        prompt_parts.append("")

        # ✅ Часть 4: Требования
        prompt_parts.append("## Requirements")
        prompt_parts.append(f"1. Use {framework} framework")
        prompt_parts.append("2. Test all public functions and methods")
        prompt_parts.append("3. Include docstrings for each test")
        prompt_parts.append("4. Follow AAA pattern (Arrange, Act, Assert)")
        prompt_parts.append("5. Use descriptive test names (test_function_scenario)")
        prompt_parts.append("")

        # ✅ Часть 5: Дополнительные требования
        prompt_parts.append("## Additional Requirements")
        if use_mocks:
            prompt_parts.append("- Use unittest.mock for mocking external dependencies")
            prompt_parts.append("- Mock database calls, API requests, file I/O")
            prompt_parts.append("- Use @patch decorator for clean mocking")
        if include_edge_cases:
            prompt_parts.append("- Include edge cases:")
            prompt_parts.append("  * Empty inputs")
            prompt_parts.append("  * None values")
            prompt_parts.append("  * Boundary values")
            prompt_parts.append("  * Invalid inputs (should raise exceptions)")
        prompt_parts.append("")

        # ✅ Часть 6: Формат вывода
        prompt_parts.append("## Output Format")
        prompt_parts.append("- Return ONLY the test code")
        prompt_parts.append("- No explanations outside the code")
        prompt_parts.append("- Include necessary imports")
        prompt_parts.append("- Make tests ready to run")
        prompt_parts.append("")
        prompt_parts.append("Generate the tests now:")

        # ✅ Собираем всё вместе
        return '\n'.join(prompt_parts)

    def check_ollama_available(self) -> bool:
        """✅ Проверяет доступность Ollama API"""
        try:
            response = requests.get(f"{self.base_url}/api/tags", timeout=5)
            return response.status_code == 200
        except requests.exceptions.ConnectionError:
            logger.warning("⚠️ Cannot connect to Ollama (ConnectionError)")
            return False
        except requests.exceptions.Timeout:
            logger.warning("⚠️ Ollama request timed out")
            return False
        except Exception as e:
            logger.warning(f"⚠️ Ollama check failed: {type(e).__name__}: {e}")
            return False

    def get_available_models(self) -> List[str]:
        """✅ Получает список доступных моделей в Ollama"""
        try:
            response = requests.get(f"{self.base_url}/api/tags", timeout=5)
            if response.status_code == 200:
                data = response.json()
                return [m['name'] for m in data.get('models', [])]
        except Exception as e:
            logger.warning(f"⚠️ Could not fetch models: {e}")
        return [self.model]  # fallback