# Generated by Django 4.2.7 on 2026-04-19 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Session', max_length=255)),
                ('python_version', models.CharField(default='3.9', max_length=10)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('ANALYZED', 'Analyzed'), ('TESTS_GENERATED', 'Tests Generated'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('report_text', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('uploaded_files', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='analyzer.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='TestGenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(default=dict)),
                ('generated_tests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('GENERATING', 'Генерируется'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgenerationtask_set', to='analyzer.analysissession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
